<?php
$_lang['setting_glossary.debug'] = 'Debug';
$_lang['setting_glossary.debug_desc'] = 'Debug-Informationen im MODX Fehlerprotokoll ausgeben.';
$_lang['setting_glossary.fullwords'] = 'Nur ganze Worte';
$_lang['setting_glossary.fullwords_desc'] = 'Nur ganze Worte eines Glossarbegriffs im Ressourcen-Inhalt ersetzen.';
$_lang['setting_glossary.html'] = 'HTML erlauben';
$_lang['setting_glossary.html_desc'] = 'HTML in der Beschreibung erlauben (Aktiviert einen Rich Text Editor im Begriff-Formular).';
$_lang['setting_glossary.resid'] = 'Glossar Ressourcen ID';
$_lang['setting_glossary.resid_desc'] = 'ID einer Ressource, die einen Glossary Snippet Aufruf enthält.';
$_lang['setting_glossary.sections'] = 'Nur in Abschnitten';
$_lang['setting_glossary.sections_desc'] = 'Glossar Begriffe nur in mit \'&lt;!— GlossaryStart --&gt;\' und \'&lt;!— GlossaryEnd --&gt;\' markierten Abschnitten ersetzen. Die Abschnittsmarkierungen lassen sich in den Einstellungen \'glossary.sectionsStart\' und \'glossary.sectionsEnd\' anpassen.';
$_lang['setting_glossary.sectionsEnd'] = 'Abschnitt Ende Markierung';
$_lang['setting_glossary.sectionsEnd_desc'] = 'Markierung am Ende eines von Glossary bearbeiteten Abschnitts. Das Beschränken auf markierte Abschnitte lässt sich in der Einstellung \'glossary.sections\' aktivieren.';
$_lang['setting_glossary.sectionsStart'] = 'Abschnitt Anfang Markierung';
$_lang['setting_glossary.sectionsStart_desc'] = 'Markierung am Anfang eines von Glossary bearbeiteten Abschnitts. Das Beschränken auf markierte Abschnitte lässt sich in der Einstellung \'glossary.sections\' aktivieren.';
$_lang['setting_glossary.tpl'] = 'Highlight Template';
$_lang['setting_glossary.tpl_desc'] = 'Template Chunk für das Higlight Element.';
$_lang['setting_glossary.disabledAttributes'] = 'Deaktivierte Attribute';
$_lang['setting_glossary.disabledAttributes_desc'] = '(Kommaseparierte Liste) Glossary ersetzt keinen Text innerhalb von diesen HTML Tag Attributen.';
